# Generated by Django 6.0.2 on 2026-02-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SaaSPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "billing_interval",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        max_length=20,
                    ),
                ),
                (
                    "max_users",
                    models.IntegerField(
                        default=1, help_text="Maximum number of team members"
                    ),
                ),
                (
                    "max_products",
                    models.IntegerField(
                        default=10, help_text="Maximum number of products"
                    ),
                ),
                (
                    "max_orders",
                    models.IntegerField(
                        default=100, help_text="Maximum number of orders per month"
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        default=dict, help_text="JSON object with feature flags"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_popular",
                    models.BooleanField(
                        default=False, help_text="Mark as popular plan badge"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("price",),
            },
        ),
    ]
